### ISSUE TITLE
How to setup firebase connection

### ISSUE THREAD

**Issue by HarshalShende** [meesnakhan/BloodBankSystem#1]

**Comment by ferozkhandev** [comment]
Brother this code is poorly written as this is my first code I wrote in Android, You should rather go for a new project. But if you have to use this as it is then you will need to login to [firebase](https://firebase.google.com/). Then you will have to perform following steps:

- Go to console from link given at right top of firebase.

- Click on Add New Project

- Add Project name

- Create Project (It will take some time).

- Hit continue and you will be redirected to firebase project page.

- There you will find Android logo right beneath getting started by adding firebase to your app. Click on that logo.

- It will require package name, enter com.bloodbanksystem.feroz as it is my app's package name. Then hit Register App.

- After that it will provide you google-services.json file. Download it and replace it with my google-services.json file at [this](https://github.com/ferozkhandev/BloodBankSystem/tree/master/app) location.

**Comment by HarshalShende** [comment]
GoogleMap features that you have added are working or not

**Comment by ferozkhandev** [comment]
Yes, those were working fine.
